### PR TITLE
I corrected the syntax for host rewrites. 

### PR DESCRIPTION
**Pull request by roblesterjr04**
the syntax was `--host-header='site' 'port'` but should be `--host-header=rewrite 'site':'port'`

### CODE REVIEW

**Comment by jn-jairo** [comment]
@roblesterjr04 As far as I know the two commands are compatible. Did you have a problem with the current command? If so could you explain so I can simulate the error?

**Comment by roblesterjr04** [comment]
There was no error. It simply didn’t forward the correct host name. It still forwarded the local host. After correcting the syntax it forwarded the app host correctly.

**Comment by jn-jairo** [comment]
Are you running inside vagrant with homestead, in the host or in another environment? I tried many environments and in all it is working, I want to know what is the difference in your case, I don't see a problem in change the command syntax, just want to understand why that difference to be sure that this change will not break the package for the others.

**Comment by roblesterjr04** [comment]
I was running it from my machine, but the app was coming from a vagrant.

I simply made the syntax match that which is documented in the post I shared.

**Comment by jn-jairo** [comment]
@roblesterjr04 you should run this and the other artisan commands inside vagrant

**Pull request closed without merging**
